'use client';
import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {AdminSectionShell} from '@/components/admin-section-shell';
import {getAdminBrowserClient,requireAdminSession} from '@/lib/admin-browser';
type Trail={id:string;name:string;slug:string;description?:string|null;sort_order:number;cover_url?:string|null;cover_focus_x?:number|null;cover_focus_y?:number|null};
type Category={id:string;name:string;slug:string;sort_order:number;trail_id?:string|null};
type GalleryCover={id:string;trail_id?:string|null;cover_url?:string|null};
const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export function AdminCategoriesNative(){
 const ref=useRef<SupabaseClient|null>(null),db=()=>getAdminBrowserClient(ref);
 const [checking,setChecking]=useState(true),[email,setEmail]=useState(''),[menuOpen,setMenuOpen]=useState(false),[trails,setTrails]=useState<Trail[]>([]),[categories,setCategories]=useState<Category[]>([]),[galleryCovers,setGalleryCovers]=useState<GalleryCover[]>([]),[focusDraft,setFocusDraft]=useState<Record<string,{x:number;y:number}>>({}),[notice,setNotice]=useState(''),[error,setError]=useState(false),[busy,setBusy]=useState(false),[trailForm,setTrailForm]=useState({id:'',name:'',slug:'',description:''}),[catForm,setCatForm]=useState({id:'',name:'',slug:'',trail_id:'',sort_order:0});
 const load=useCallback(async()=>{const [a,b,c]=await Promise.all([db().from('gallery_trails').select('*').order('sort_order').order('name'),db().from('categories').select('*').order('sort_order').order('name'),db().from('galleries').select('id,trail_id,cover_url').order('sort_order')]);const failure=a.error||b.error||c.error;setError(Boolean(failure));setNotice(failure?.message||'');const next=(a.data||[]) as Trail[];setTrails(next);setCategories((b.data||[]) as Category[]);setGalleryCovers((c.data||[]) as GalleryCover[]);setFocusDraft(Object.fromEntries(next.map(t=>[t.id,{x:Number(t.cover_focus_x??50),y:Number(t.cover_focus_y??50)}])))},[]);
 useEffect(()=>{requireAdminSession(db()).then(session=>{if(!session)return location.replace('/admin');setEmail(session.user.email||'');setChecking(false);load()})},[load]);
 async function saveTrail(event:FormEvent){event.preventDefault();const name=trailForm.name.trim().slice(0,100),slug=slugify(trailForm.slug||name).slice(0,120);if(!name||!slug)return;setBusy(true);const payload={name,slug,description:trailForm.description.trim().slice(0,240)||null,sort_order:trailForm.id?trails.find(x=>x.id===trailForm.id)?.sort_order||0:trails.length*10},result=trailForm.id?await db().from('gallery_trails').update(payload).eq('id',trailForm.id):await db().from('gallery_trails').insert(payload);setBusy(false);setError(Boolean(result.error));setNotice(result.error?.message||'Trilha salva.');if(!result.error){setTrailForm({id:'',name:'',slug:'',description:''});load()}}
 async function saveCategory(event:FormEvent){event.preventDefault();const name=catForm.name.trim().slice(0,80),slug=slugify(catForm.slug||name).slice(0,120);if(!name||!slug)return;setBusy(true);const payload={name,slug,trail_id:catForm.trail_id||null,sort_order:Number(catForm.sort_order)||0,published:true},result=catForm.id?await db().from('categories').update(payload).eq('id',catForm.id):await db().from('categories').insert(payload);setBusy(false);setError(Boolean(result.error));setNotice(result.error?.message||'Categoria salva.');if(!result.error){setCatForm({id:'',name:'',slug:'',trail_id:'',sort_order:0});load()}}
 async function remove(table:'gallery_trails'|'categories',id:string,label:string){if(!confirm(`Excluir “${label}”?`))return;const result=await db().from(table).delete().eq('id',id);setError(Boolean(result.error));setNotice(result.error?.message||'Item excluído.');if(!result.error)load()}
 async function move(item:Trail,direction:number){const index=trails.findIndex(x=>x.id===item.id),other=trails[index+direction];if(!other)return;setBusy(true);const results=await Promise.all([db().from('gallery_trails').update({sort_order:other.sort_order}).eq('id',item.id),db().from('gallery_trails').update({sort_order:item.sort_order}).eq('id',other.id)]),failure=results.find(x=>x.error)?.error;setBusy(false);setError(Boolean(failure));setNotice(failure?.message||'Ordem das trilhas atualizada.');if(!failure)load()}
 async function saveFocus(item:Trail){const focus=focusDraft[item.id]||{x:50,y:50},result=await db().from('gallery_trails').update({cover_focus_x:focus.x,cover_focus_y:focus.y}).eq('id',item.id);setError(Boolean(result.error));setNotice(result.error?.message||'Enquadramento da trilha salvo.');if(!result.error)load()}
 async function logout(){await db().auth.signOut();location.replace('/admin')}
 if(checking)return <div className="admin-native-loading">Verificando sessão administrativa…</div>;
 return <AdminSectionShell active="/admin/categorias" email={email} eyebrow="Organização" title="Categorias" menuOpen={menuOpen} setMenuOpen={setMenuOpen} onLogout={logout}><section className="admin-view">{notice&&<div className={`flash ${error?'erro':'sucesso'}`}>{notice}</div>}
  <div className="panel"><h2>Trilhas</h2><form className="inline-form" onSubmit={saveTrail}><input placeholder="Nome da trilha" value={trailForm.name} onChange={e=>setTrailForm({...trailForm,name:e.target.value,slug:trailForm.id?trailForm.slug:slugify(e.target.value)})}/><input placeholder="slug" value={trailForm.slug} onChange={e=>setTrailForm({...trailForm,slug:slugify(e.target.value)})}/><input placeholder="Descrição" value={trailForm.description} onChange={e=>setTrailForm({...trailForm,description:e.target.value})}/><button className="btn btn-accent" disabled={busy}>Salvar trilha</button></form>
   <div className="trail-admin-grid">{trails.map((trail,index)=>{const cover=trail.cover_url||galleryCovers.find(g=>g.trail_id===trail.id)?.cover_url||'',focus=focusDraft[trail.id]||{x:50,y:50};const change=(key:'x'|'y',value:number)=>setFocusDraft(all=>({...all,[trail.id]:{...focus,[key]:value}}));return <article className="trail-admin-row" key={trail.id}><div className="trail-admin-identity"><strong>{trail.name}</strong><span>/{trail.slug}</span></div><div className="trail-admin-count">{categories.filter(c=>c.trail_id===trail.id).length} categorias</div><div className="trail-order-actions"><button className="small-btn" disabled={!index||busy} onClick={()=>move(trail,-1)}>←</button><span>{index+1}</span><button className="small-btn" disabled={index===trails.length-1||busy} onClick={()=>move(trail,1)}>→</button></div><div className="trail-focus-editor"><div className={`cover-focus-preview ${cover?'':'empty'}`} style={{backgroundImage:cover?`url("${cover}")`:'none',backgroundPosition:`${focus.x}% ${focus.y}%`}} onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();setFocusDraft(all=>({...all,[trail.id]:{x:Math.round((event.clientX-rect.left)/rect.width*100),y:Math.round((event.clientY-rect.top)/rect.height*100)}}))}}><span className="cover-focus-marker" style={{left:`${focus.x}%`,top:`${focus.y}%`}}/></div><label>Horizontal <input type="range" min="0" max="100" value={focus.x} onChange={e=>change('x',Number(e.target.value))}/><output>{focus.x}%</output></label><label>Vertical <input type="range" min="0" max="100" value={focus.y} onChange={e=>change('y',Number(e.target.value))}/><output>{focus.y}%</output></label></div><div className="trail-admin-actions"><button className="small-btn" onClick={()=>saveFocus(trail)}>Salvar enquadramento</button><button className="small-btn" onClick={()=>setTrailForm({id:trail.id,name:trail.name,slug:trail.slug,description:trail.description||''})}>Editar</button><button className="small-btn danger-btn" onClick={()=>remove('gallery_trails',trail.id,trail.name)}>Excluir</button></div></article>})}</div>
  </div>
  <div className="panel"><h2>Categorias</h2><form className="inline-form" onSubmit={saveCategory}><input placeholder="Nome" value={catForm.name} onChange={e=>setCatForm({...catForm,name:e.target.value,slug:catForm.id?catForm.slug:slugify(e.target.value)})}/><input placeholder="slug" value={catForm.slug} onChange={e=>setCatForm({...catForm,slug:slugify(e.target.value)})}/><select value={catForm.trail_id} onChange={e=>setCatForm({...catForm,trail_id:e.target.value})}><option value="">Sem trilha</option>{trails.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input type="number" value={catForm.sort_order} onChange={e=>setCatForm({...catForm,sort_order:Number(e.target.value)})}/><button className="btn btn-accent" disabled={busy}>Salvar</button></form><div className="category-list">{categories.map(category=><div className="category-row" key={category.id}><strong>{category.name}</strong><span>/{category.slug}</span><span>{category.sort_order}</span><div className="card-actions"><button className="small-btn" onClick={()=>setCatForm({id:category.id,name:category.name,slug:category.slug,trail_id:category.trail_id||'',sort_order:category.sort_order})}>Editar</button><button className="small-btn danger-btn" onClick={()=>remove('categories',category.id,category.name)}>Excluir</button></div></div>)}</div></div>
 </section></AdminSectionShell>
}
