'use client';
import {FormEvent,useCallback,useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {AdminSectionShell} from '@/components/admin-section-shell';
import {getAdminBrowserClient,requireAdminSession} from '@/lib/admin-browser';
type Settings={id?:string;site_name:string;email:string;whatsapp:string;instagram_url:string;location:string;specialty:string;availability:string;footer_text:string};
const empty:Settings={site_name:'',email:'',whatsapp:'',instagram_url:'',location:'',specialty:'',availability:'',footer_text:''};
export function AdminSettings(){
 const ref=useRef<SupabaseClient|null>(null),db=()=>getAdminBrowserClient(ref);const [checking,setChecking]=useState(true),[email,setEmail]=useState(''),[menuOpen,setMenuOpen]=useState(false),[form,setForm]=useState<Settings>(empty),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false);
 const load=useCallback(async()=>{const result=await db().from('site_settings').select('*').limit(1).maybeSingle();if(result.error){setError(true);setNotice(result.error.message)}else if(result.data)setForm({...empty,...result.data})},[]);
 useEffect(()=>{requireAdminSession(db()).then(session=>{if(!session)return location.replace('/admin');setEmail(session.user.email||'');setChecking(false);load()})},[load]);
 const field=(key:keyof Settings,value:string)=>setForm(current=>({...current,[key]:value}));
 async function save(event:FormEvent){event.preventDefault();const digits=form.whatsapp.replace(/\D/g,'');if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)){setError(true);return setNotice('Informe um e-mail válido.')}if(digits&&(digits.length<7||digits.length>15)){setError(true);return setNotice('O WhatsApp deve conter entre 7 e 15 dígitos.')}setBusy(true);const payload={site_name:form.site_name.trim().slice(0,120),email:form.email.trim().toLowerCase().slice(0,254),whatsapp:digits,instagram_url:form.instagram_url.trim().slice(0,2048),location:form.location.trim().slice(0,160),specialty:form.specialty.trim().slice(0,160),availability:form.availability.trim().slice(0,160),footer_text:form.footer_text.trim().slice(0,1000),updated_at:new Date().toISOString()};const result=form.id?await db().from('site_settings').update(payload).eq('id',form.id).select().single():await db().from('site_settings').insert(payload).select().single();setBusy(false);setError(Boolean(result.error));setNotice(result.error?.message||'Configurações salvas.');if(result.data)setForm({...empty,...result.data})}
 async function logout(){await db().auth.signOut();location.replace('/admin')}if(checking)return <div className="admin-native-loading">Verificando sessão administrativa…</div>;
 const fields:[keyof Settings,string][]=[['site_name','Nome do site'],['email','E-mail'],['whatsapp','WhatsApp'],['instagram_url','Instagram'],['location','Localização'],['specialty','Especialidade'],['availability','Disponibilidade']];
 return <AdminSectionShell active="/admin/configuracoes" email={email} eyebrow="Sistema" title="Configurações" menuOpen={menuOpen} setMenuOpen={setMenuOpen} onLogout={logout}><section className="admin-view"><div className="panel"><div className="panel-head"><div><p className="section-eyebrow">Dados gerais</p><h2>Informações do estúdio</h2></div></div>{notice&&<div className={`flash ${error?'erro':'sucesso'}`}>{notice}</div>}<form className="admin-native-form" onSubmit={save}>{fields.map(([key,label])=><label className="field" key={key}><span>{label}</span><input value={form[key]||''} onChange={e=>field(key,e.target.value)}/></label>)}<label className="field admin-native-full"><span>Texto do rodapé</span><textarea rows={5} maxLength={1000} value={form.footer_text} onChange={e=>field('footer_text',e.target.value)}/></label><div className="form-actions admin-native-full"><button className="btn btn-accent" disabled={busy}>Salvar configurações</button></div></form></div></section></AdminSectionShell>}
