'use client';
import {ChangeEvent,ReactNode,useState} from 'react';
type Map=Record<string,any>;
type PanelKey='hero'|'header'|'animations'|'general'|'whatsapp'|'galleries'|'client';
const initialOrder:PanelKey[]=['hero','header','animations','general','whatsapp','galleries','client'];
const options=(values:[string,string][])=>values.map(([value,label])=><option value={value} key={value}>{label}</option>);
function Field({label,children,full=false}:{label:string;children:ReactNode;full?:boolean}){return <label className={`field ${full?'field-full':''}`}><span>{label}</span>{children}</label>}
function Range({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(value:number)=>void}){return <Field label={label}><div className="design-range"><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><output>{value}{label.toLowerCase().includes('tempo')?' s':label.toLowerCase().includes('escala')?'%':' px'}</output></div></Field>}
function Panel({title,copy,open,onToggle,children,onSave,busy,draggable,onDragStart,onDrop}:{title:string;copy:string;open:boolean;onToggle:()=>void;children:ReactNode;onSave:()=>void;busy:boolean;draggable:boolean;onDragStart:()=>void;onDrop:()=>void}){return <section className={`design-stack-panel ${open?'is-open':''}`} draggable={draggable} onDragStart={onDragStart} onDragOver={e=>{if(draggable)e.preventDefault()}} onDrop={onDrop}><button className="design-stack-toggle" type="button" aria-expanded={open} onClick={onToggle}><span><strong>{title}</strong><small>{copy}</small></span><i>{open?'⌄':'›'}</i></button>{open&&<div className="design-stack-body"><div className="admin-native-form">{children}</div><div className="form-actions design-panel-actions"><button type="button" className="btn btn-accent" disabled={busy} onClick={onSave}>Salvar painel no rascunho</button></div></div>}</section>}
export function AdminDesignStudio(p:Map){
 const {config,hero,recent,set,h,r,upload,addSlides,updateSlide,moveSlide,saveDraft,busy}=p;
 const [order,setOrder]=useState<PanelKey[]>(initialOrder),[open,setOpen]=useState<Record<PanelKey,boolean>>({hero:false,header:false,animations:false,general:false,whatsapp:false,galleries:false,client:false}),[reorder,setReorder]=useState(false),[dragged,setDragged]=useState<PanelKey|null>(null);
 const toggle=(key:PanelKey)=>setOpen(all=>({...all,[key]:!all[key]}));
 const drop=(key:PanelKey)=>{if(!dragged||dragged===key)return;setOrder(all=>{const next=all.filter(x=>x!==dragged),at=next.indexOf(key);next.splice(at,0,dragged);return next});setDragged(null)};
 const panels:Record<PanelKey,{title:string;copy:string;body:ReactNode}>={
  hero:{title:'Imagem principal',copy:'Escolha entre uma foto estática ou um slideshow para o topo da página inicial.',body:<>
   <div className="field field-full hero-mode-field"><span>Modo da imagem principal</span><div className="hero-mode-switch"><label><input type="radio" checked={(hero.mode||'static')==='static'} onChange={()=>h('mode','static')}/> Foto estática</label><label><input type="radio" checked={hero.mode==='slideshow'} onChange={()=>h('mode','slideshow')}/> Slideshow</label></div></div>
   {(hero.mode||'static')==='static'?<><Field label="Imagem principal" full><label className="hero-upload-drop">Clique para enviar a foto principal<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>upload(e.target.files?.[0],'hero',(url:string)=>h('desktop_image',url))}/></label></Field><Field label="Imagem para celular (opcional)" full><label className="hero-upload-drop">Clique para enviar a foto para celular<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>upload(e.target.files?.[0],'hero-mobile',(url:string)=>h('mobile_image',url))}/></label></Field><Field label="Texto alternativo" full><input value={hero.image_alt||''} onChange={e=>h('image_alt',e.target.value)}/></Field>
   <div className="field field-full hero-static-preview-row"><div><p className="section-eyebrow">Prévia principal</p><div className={`focal-preview ${hero.desktop_image?'':'empty'}`} style={{backgroundImage:hero.desktop_image?`url("${hero.desktop_image}")`:'none',backgroundPosition:`${hero.static_focus_x??50}% ${hero.static_focus_y??50}%`}}><span className="focal-marker" style={{left:`${hero.static_focus_x??50}%`,top:`${hero.static_focus_y??50}%`}}/></div></div><div><Range label="Foco horizontal" value={Number(hero.static_focus_x??50)} min={0} max={100} onChange={v=>h('static_focus_x',v)}/><Range label="Foco vertical" value={Number(hero.static_focus_y??50)} min={0} max={100} onChange={v=>h('static_focus_y',v)}/></div><div><p className="section-eyebrow">Prévia celular</p><div className={`hero-static-mobile-preview ${hero.mobile_image||hero.desktop_image?'':'empty'}`} style={{backgroundImage:`url("${hero.mobile_image||hero.desktop_image||''}")`,backgroundPosition:`${hero.static_mobile_focus_x??50}% ${hero.static_mobile_focus_y??50}%`}}><span className="focal-marker"/></div><Range label="Foco horizontal celular" value={Number(hero.static_mobile_focus_x??50)} min={0} max={100} onChange={v=>h('static_mobile_focus_x',v)}/><Range label="Foco vertical celular" value={Number(hero.static_mobile_focus_y??50)} min={0} max={100} onChange={v=>h('static_mobile_focus_y',v)}/></div></div></>:<>
   <Field label="Adicionar imagens ao slideshow" full><label className="hero-upload-drop">Selecionar fotografias<input hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={addSlides}/></label></Field><Field label="Encaixe"><select value={hero.slide_fit||'cover'} onChange={e=>h('slide_fit',e.target.value)}>{options([['cover','Preencher'],['contain','Conter']])}</select></Field><Field label="Animação"><select value={hero.slide_animation||'fade'} onChange={e=>h('slide_animation',e.target.value)}>{options([['fade','Dissolver'],['slide','Deslizar'],['zoom','Zoom suave']])}</select></Field><Range label="Tempo de cada foto" value={Number(hero.slide_interval??5)} min={2} max={30} step={.5} onChange={v=>h('slide_interval',v)}/><Range label="Tempo da transição" value={Number(hero.slide_transition??1.2)} min={.3} max={5} step={.1} onChange={v=>h('slide_transition',v)}/><div className="field field-full hero-slides-admin">{(hero.slides||[]).map((slide:Map,index:number)=><article key={slide.id||index}><img src={slide.url} alt=""/><input value={slide.alt||''} placeholder="Texto alternativo" onChange={e=>updateSlide(index,'alt',e.target.value)}/><div className="card-actions"><button type="button" className="small-btn" disabled={!index} onClick={()=>moveSlide(index,-1)}>↑</button><button type="button" className="small-btn" disabled={index===(hero.slides||[]).length-1} onClick={()=>moveSlide(index,1)}>↓</button><button type="button" className="small-btn" onClick={()=>updateSlide(index,'published',slide.published===false)}>{slide.published===false?'Mostrar':'Ocultar'}</button><button type="button" className="small-btn danger-btn" onClick={()=>h('slides',(hero.slides||[]).filter((_:Map,i:number)=>i!==index))}>Excluir</button></div></article>)}</div></>}
   <Field label="Texto acima do título"><input value={hero.eyebrow||''} onChange={e=>h('eyebrow',e.target.value)}/></Field><Field label="Título"><textarea rows={3} value={hero.title||''} onChange={e=>h('title',e.target.value)}/></Field><Field label="Descrição" full><textarea rows={3} value={hero.description||''} onChange={e=>h('description',e.target.value)}/></Field><Field label="Botão principal — texto"><input value={hero.primary_button?.text||''} onChange={e=>h('primary_button',{...hero.primary_button,text:e.target.value})}/></Field><Field label="Botão principal — link"><input value={hero.primary_button?.url||''} onChange={e=>h('primary_button',{...hero.primary_button,url:e.target.value})}/></Field><Field label="Botão secundário — texto"><input value={hero.secondary_button?.text||''} onChange={e=>h('secondary_button',{...hero.secondary_button,text:e.target.value})}/></Field><Field label="Botão secundário — link"><input value={hero.secondary_button?.url||''} onChange={e=>h('secondary_button',{...hero.secondary_button,url:e.target.value})}/></Field><Field label="Informações do rodapé (Rótulo | Valor)" full><textarea rows={3} value={(hero.meta||[]).map((x:Map)=>`${x.label} | ${x.value}`).join('\n')} onChange={e=>h('meta',e.target.value.split('\n').filter(Boolean).map(line=>{const [label,...value]=line.split('|');return {label:label.trim(),value:value.join('|').trim()}}))}/></Field>
   <h3 className="field-full">Trabalhos recentes</h3><Field label="Texto superior"><input value={recent.eyebrow||''} onChange={e=>r('eyebrow',e.target.value)}/></Field><Field label="Título"><input value={recent.title||''} onChange={e=>r('title',e.target.value)}/></Field><Field label="Quantidade"><input type="number" min={1} max={24} value={recent.gallery_limit??6} onChange={e=>r('gallery_limit',Number(e.target.value))}/></Field><Field label="Botão — texto"><input value={recent.button?.text||''} onChange={e=>r('button',{...recent.button,text:e.target.value})}/></Field><Field label="Botão — link"><input value={recent.button?.url||''} onChange={e=>r('button',{...recent.button,url:e.target.value})}/></Field></>},
  header:{title:'Cabeçalho',copy:'Aparência, posição e comportamento do menu público.',body:<>{[['nav_style','Aparência do menu',[['auto','Automático do site'],['transparent','Transparente'],['solid','Sólido']]],['nav_position','Comportamento',[['fixed','Fixo no topo'],['static','Acompanha a página']]],['nav_density','Densidade',[['compact','Compacto'],['normal','Normal'],['airy','Espaçado']]],['nav_cta','Área do Cliente',[['outline','Contorno'],['filled','Preenchido'],['hidden','Ocultar']]]].map(([key,label,values]:any)=><Field label={label} key={key}><select value={config[key]} onChange={e=>set(key,e.target.value)}>{options(values)}</select></Field>)}<Range label="Escala da marca" value={Number(config.logo_scale??100)} min={85} max={120} onChange={v=>set('logo_scale',v)}/><Range label="Desfoque do menu" value={Number(config.nav_blur??0)} min={0} max={18} onChange={v=>set('nav_blur',v)}/></>},
  animations:{title:'Animações de transição',copy:'Movimento ao abrir ou trocar de página no computador e no celular.',body:<>{[['page_animation','Entrada da página',[['none','Nenhuma'],['fade','Esmaecer'],['fade-up','Subir suavemente'],['soft','Suave premium']]],['section_animation','Entrada das seções',[['none','Nenhuma'],['fade','Esmaecer'],['fade-up','Subir suavemente']]],['image_hover','Movimento nas fotos',[['site','Padrão do site'],['none','Sem movimento'],['zoom','Zoom suave'],['lift','Elevar']]],['motion_speed','Velocidade',[['fast','Rápida'],['normal','Normal'],['slow','Lenta']]]].map(([key,label,values]:any)=><Field label={label} key={key}><select value={config[key]} onChange={e=>set(key,e.target.value)}>{options(values)}</select></Field>)}<div className="field field-full"><button type="button" className="small-btn" onClick={()=>p.replayPreview?.()}>Repetir animações na prévia</button></div></>},
  general:{title:'Estilo geral',copy:'Escala dos títulos, largura, espaçamento e intensidade da imagem.',body:<>{[['type_scale','Escala dos títulos',90,115],['content_width','Largura do conteúdo',1040,1500],['section_space','Espaço entre seções',72,160],['hero_overlay','Intensidade do Hero',0,70]].map(([key,label,min,max]:any)=><Range key={key} label={label} value={Number(config[key])} min={min} max={max} onChange={v=>set(key,v)}/>)}</>},
  whatsapp:{title:'WhatsApp — botão flutuante',copy:'Configure o contacto direto apresentado no site público.',body:<><Field label="Exibir botão"><input type="checkbox" checked={config.whatsapp_enabled!==false} onChange={e=>set('whatsapp_enabled',e.target.checked)}/></Field><Field label="Número com indicativo"><input value={config.whatsapp_number||''} onChange={e=>set('whatsapp_number',e.target.value.replace(/\D/g,''))}/></Field><Field label="Mensagem inicial" full><textarea rows={3} value={config.whatsapp_message||''} onChange={e=>set('whatsapp_message',e.target.value)}/></Field><Field label="Posição"><select value={config.whatsapp_position||'right'} onChange={e=>set('whatsapp_position',e.target.value)}>{options([['right','Direita'],['left','Esquerda']])}</select></Field><Field label="Estilo"><select value={config.whatsapp_style||'editorial'} onChange={e=>set('whatsapp_style',e.target.value)}>{options([['editorial','Editorial'],['minimal','Minimalista'],['classic','WhatsApp clássico']])}</select></Field><div className="field field-full"><span>Mostrar nas páginas</span><div className="design-page-checks">{['inicio','galeria','sobre','contato'].map(page=><label key={page}><input type="checkbox" checked={(config.whatsapp_pages||[]).includes(page)} onChange={e=>set('whatsapp_pages',e.target.checked?[...new Set([...(config.whatsapp_pages||[]),page])]:(config.whatsapp_pages||[]).filter((x:string)=>x!==page))}/> {page}</label>)}</div></div></>},
  galleries:{title:'Galerias',copy:'Espaçamento e cantos das fotografias.',body:<><Range label="Espaço entre fotos" value={Number(config.gallery_gap??2)} min={0} max={16} onChange={v=>set('gallery_gap',v)}/><Range label="Cantos das imagens" value={Number(config.image_radius??0)} min={0} max={18} onChange={v=>set('image_radius',v)}/></>},
  client:{title:'Área do Cliente',copy:'Layout de acesso, galeria privada, imagem e textos.',body:<>{[['client_layout','Layout de acesso',[['editorial-split','Editorial dividido'],['centered','Minimalista central'],['fullscreen','Imagem em tela cheia']]],['client_gallery_style','Estilo da galeria',[['editorial','Grade editorial'],['clean','Grade limpa'],['masonry','Masonry']]],['client_photo_size','Tamanho das fotografias',[['compact','Compacto'],['medium','Médio'],['large','Grande']]],['client_typography','Tipografia',[['classic','Clássica'],['editorial','Editorial'],['minimal','Minimalista']]],['client_border','Bordas',[['fine','Fina'],['none','Sem borda'],['soft','Suave']]]].map(([key,label,values]:any)=><Field label={label} key={key}><select value={config[key]} onChange={e=>set(key,e.target.value)}>{options(values)}</select></Field>)}<Field label="Imagem da tela de acesso" full><label className="hero-upload-drop">Selecionar imagem<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>upload(e.target.files?.[0],'client-area',(url:string)=>set('client_access_image',url))}/></label>{config.client_access_image&&<div className="focal-preview" style={{backgroundImage:`url("${config.client_access_image}")`,backgroundPosition:`${config.client_focus_x??50}% ${config.client_focus_y??50}%`}}><span className="focal-marker"/></div>}</Field><Range label="Foco horizontal" value={Number(config.client_focus_x??50)} min={0} max={100} onChange={v=>set('client_focus_x',v)}/><Range label="Foco vertical" value={Number(config.client_focus_y??50)} min={0} max={100} onChange={v=>set('client_focus_y',v)}/>{p.clientTextFields.map(([key,label]:[string,string])=><Field label={label} key={key}><input value={config[key]||''} onChange={e=>set(key,e.target.value)}/></Field>)}</>}
 };
 return <div className="design-inline-panels"><button type="button" className={`admin-menu-reorder design-panels-reorder ${reorder?'active':''}`} onClick={()=>setReorder(v=>!v)}>{reorder?'Concluir reordenação':'Reordenar painéis'}</button>{order.map(key=>{const panel=panels[key];return <Panel key={key} title={panel.title} copy={panel.copy} open={open[key]} onToggle={()=>toggle(key)} onSave={saveDraft} busy={busy} draggable={reorder} onDragStart={()=>setDragged(key)} onDrop={()=>drop(key)}>{panel.body}</Panel>})}</div>
}
