'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import JSZip from 'jszip';
import { createSupabaseBrowserClient } from '@/lib/supabase/browser';

type ClientPhoto = { id: string; url: string; selecionada?: boolean };
type ClientSession = {
  id: string;
  titulo: string;
  status?: string;
  fotos?: ClientPhoto[];
  selected_photo_numbers?: Array<string | number>;
  selection_thank_you_image_url?: string;
  selection_thank_you_message?: string;
};

const normalizeStatus = (status?: string) => status === 'selecionado' ? 'selecao_finalizada' : status === 'entregue' ? 'fotos_disponiveis' : status || 'preparando';
const statusOrder: Record<string, number> = { preparando:-1, aguardando_selecao:0, selecao_finalizada:1, em_edicao:1, fotos_disponiveis:2 };
const statusTexts: Record<string,string> = {
  preparando:'Suas fotos estão sendo preparadas', aguardando_selecao:'Escolha suas fotos favoritas',
  selecao_finalizada:'Seleção enviada — aguardando edição', em_edicao:'Suas fotografias estão em edição',
  fotos_disponiveis:'Suas fotos estão prontas!'
};

function downloadBlob(blob: Blob, name: string) {
  const url=URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download=name;
  document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
}

export function ClientAreaExperience() {
  const supabase=useMemo(()=>typeof window==='undefined'?({} as ReturnType<typeof createSupabaseBrowserClient>):createSupabaseBrowserClient(),[]);
  const [slug,setSlug]=useState(''); const [code,setCode]=useState(''); const [showCode,setShowCode]=useState(false);
  const [message,setMessage]=useState(''); const [error,setError]=useState(false); const [busy,setBusy]=useState(false);
  const [session,setSession]=useState<ClientSession|null>(null); const [selected,setSelected]=useState<Set<string>>(new Set());
  const [lightbox,setLightbox]=useState<number|null>(null); const [confirm,setConfirm]=useState(false); const [downloadMessage,setDownloadMessage]=useState('');
  const barTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const photos=session?.fotos||[]; const status=normalizeStatus(session?.status); const currentStage=statusOrder[status]??-1;

  useEffect(()=>{const protect=(event:Event)=>{if((event.target as Element|null)?.closest?.('.protegida'))event.preventDefault()};document.addEventListener('contextmenu',protect);document.addEventListener('dragstart',protect);return()=>{document.removeEventListener('contextmenu',protect);document.removeEventListener('dragstart',protect)}},[]);
  useEffect(()=>{document.body.style.overflow=lightbox!==null||confirm?'hidden':'';return()=>{document.body.style.overflow=''}},[lightbox,confirm]);
  useEffect(()=>{if(status!=='aguardando_selecao')return;const onScroll=()=>{const bar=document.getElementById('barra-selecao');bar?.classList.add('oculta');if(barTimer.current)clearTimeout(barTimer.current);barTimer.current=setTimeout(()=>bar?.classList.remove('oculta'),500)};window.addEventListener('scroll',onScroll,{passive:true});return()=>{window.removeEventListener('scroll',onScroll);if(barTimer.current)clearTimeout(barTimer.current)}},[status]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){if(confirm)setConfirm(false);else setLightbox(null)}if(lightbox!==null&&photos.length){if(event.key==='ArrowRight')setLightbox((lightbox+1)%photos.length);if(event.key==='ArrowLeft')setLightbox((lightbox-1+photos.length)%photos.length)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[confirm,lightbox,photos.length]);

  async function enter(event:FormEvent){event.preventDefault();setBusy(true);setError(false);setMessage('Verificando...');try{const base=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!base||!key)throw new Error('Configuração indisponível.');const response=await fetch(`${base}/functions/v1/client-access`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({slug:slug.trim(),codigo:code.trim()})});const data=await response.json().catch(()=>null);if(!data||data.erro){setError(true);setMessage(data?.rate_limited?'Muitas tentativas. Aguarde alguns minutos e tente novamente.':data?.erro==='Não foi possível verificar o acesso agora.'?data.erro:'Link ou código inválido. Confira com o fotógrafo.');return}const next=data as ClientSession;setSession(next);setSelected(new Set((next.fotos||[]).filter(photo=>photo.selecionada).map(photo=>photo.id)));setMessage('')}catch(err){console.error('Falha ao verificar acesso:',err);setError(true);setMessage('Não foi possível verificar o acesso agora.')}finally{setBusy(false)}}
  function toggle(id:string){setSelected(previous=>{const next=new Set(previous);next.has(id)?next.delete(id):next.add(id);return next})}
  async function saveSelection(){if(!session||!selected.size)return;setBusy(true);setError(false);setMessage('Enviando sua seleção...');try{const ids=Array.from(selected);const {data,error:rpcError}=await supabase.rpc('salvar_selecao',{p_ensaio_id:session.id,p_codigo:code.trim(),p_foto_ids:ids});if(rpcError||data?.erro)throw new Error(data?.erro||rpcError?.message||'Erro desconhecido.');setSession({...session,status:data?.status||'selecao_finalizada',fotos:photos.map(photo=>({...photo,selecionada:selected.has(photo.id)}))});setConfirm(false);setMessage('');try{const {data:notification,error:notificationError}=await supabase.functions.invoke('ensaio-notifications',{body:{action:'selection_finalized',ensaio_id:session.id,codigo:code.trim()}});if(notificationError||notification?.error)console.warn('[area-cliente] Seleção salva, mas a notificação ficou pendente.',notificationError||notification)}catch(notificationError){console.warn('[area-cliente] Seleção salva, mas a notificação ficou pendente.',notificationError)}}catch(err){console.error('[area-cliente] Falha ao salvar seleção:',err);setError(true);setMessage(err instanceof Error?err.message:'Não foi possível concluir a seleção. Tente novamente.')}finally{setBusy(false)}}
  async function downloadOne(photo:ClientPhoto,index:number){try{const response=await fetch(photo.url);if(!response.ok)throw new Error();downloadBlob(await response.blob(),`foto-${index+1}.jpg`)}catch{window.open(photo.url,'_blank','noopener')}}
  async function downloadAll(){setBusy(true);setDownloadMessage('');try{const zip=new JSZip();for(let index=0;index<photos.length;index++){setDownloadMessage(`Preparando... (${index+1}/${photos.length})`);const response=await fetch(photos[index].url);if(!response.ok)throw new Error();zip.file(`foto-${index+1}.jpg`,await response.blob())}setDownloadMessage('Compactando...');downloadBlob(await zip.generateAsync({type:'blob'}),'fotos-rangel-santos.zip');setDownloadMessage('')}catch{setDownloadMessage('Não foi possível compactar. Tente baixar as fotos uma a uma.')}finally{setBusy(false)}}

  if(!session)return <main id="acesso-screen" className="cliente-wrap client-access-wrap"><div className="client-access-shell"><div className="client-access-visual" aria-hidden="true"><div className="client-access-visual-copy"><p id="client-visual-text">Retratos guardados com cuidado.<br/>Um espaço reservado só para você.</p></div></div><section className="acesso-box client-access-panel"><div className="client-access-copy"><p className="section-eyebrow" id="client-access-eyebrow">Área privada</p><h1 className="client-access-title"><span id="client-access-title-main">Sua sessão,</span><br/><em id="client-access-title-emphasis">em um espaço só seu.</em></h1><p className="client-access-description" id="client-access-description">Acesse sua galeria para selecionar fotografias, acompanhar a edição e receber seus arquivos finais.</p></div><form className="client-access-form" onSubmit={enter}><div className="field"><label htmlFor="input-slug" id="client-login-label">Login</label><input id="input-slug" value={slug} onChange={e=>setSlug(e.target.value)} required autoComplete="username"/></div><div className="field"><label htmlFor="input-codigo" id="client-password-label">Senha</label><div className="client-password-field"><input type={showCode?'text':'password'} id="input-codigo" value={code} onChange={e=>setCode(e.target.value)} required autoComplete="current-password"/><button type="button" id="btn-toggle-senha" className="client-password-toggle" onClick={()=>setShowCode(value=>!value)} aria-label={showCode?'Ocultar senha':'Mostrar senha'}>{showCode?'🙈':'👁'}</button></div></div><button type="submit" className="btn btn-accent client-access-submit" id="client-access-submit" disabled={busy}>Acessar minha galeria</button><p className={`msg ${error?'erro':''}`}>{message}</p><div className="client-access-secure"><span>⌁</span><span id="client-access-secure-text">Acesso privado e protegido</span></div></form></section></div></main>;

  const selectedPhotos=photos.filter(photo=>photo.selecionada);const selectedCount=selectedPhotos.length||(session.selected_photo_numbers||[]).length;
  return <main id="galeria-screen" className="cliente-wrap client-gallery-wrap"><header className="client-gallery-header"><div><p className="section-eyebrow" id="client-gallery-eyebrow">Sua experiência</p><h1 className="section-title" id="cliente-titulo">{session.titulo}</h1><p className="client-gallery-status" id="cliente-status">{statusTexts[status]||''}</p></div><div className="client-journey" aria-label="Etapas do ensaio">{[['Seleção','Escolha'],['Edição','Tratamento'],['Entrega','Final']].map(([title,sub],index)=><div key={title} className={`client-stage-card ${index===currentStage?'is-current':''} ${index<currentStage?'is-complete':''}`}><span>{String(index+1).padStart(2,'0')}</span><strong>{title}</strong><small>{sub}</small></div>)}</div></header><div id="conteudo-galeria">
    {status==='preparando'&&<div className="client-centered-state"><p className="client-state-title">Só um instante...</p><p>O Rangel ainda está preparando as fotos da sua sessão. Assim que estiverem prontas para você escolher, elas vão aparecer aqui automaticamente.</p></div>}
    {status==='fotos_disponiveis'&&<><div className="section-head client-delivery-head"><div><p className="client-state-title">Suas fotos estão prontas! 🤍</p><p>Foi um prazer registrar esse momento com você. Obrigado pela confiança — espero que essas fotos te façam sentir exatamente como você é.</p></div><button className="btn btn-accent" onClick={downloadAll} disabled={busy}>Baixar tudo (.zip)</button></div><p className={`msg ${downloadMessage.startsWith('Não')?'erro':''}`}>{downloadMessage}</p><div className="grid client-gallery-grid">{photos.map((photo,index)=><div className="frame" key={photo.id}><img src={photo.url} alt={`Foto final ${index+1}`}/><div className="frame-caption client-download-caption"><button className="btn btn-accent" onClick={()=>downloadOne(photo,index)}>Baixar</button></div></div>)}</div></>}
    {['selecao_finalizada','em_edicao'].includes(status)&&<div className="client-centered-state">{status==='em_edicao'&&session.selection_thank_you_image_url&&<img className="client-thank-you-image" src={session.selection_thank_you_image_url} alt="Agradecimento pela seleção"/>}<p className="client-state-title">Obrigado pela sua escolha!</p><p>{session.selection_thank_you_message||`Recebemos sua seleção de ${selectedCount} foto${selectedCount===1?'':'s'}. Agora é com o Rangel — assim que as fotos estiverem prontas e tratadas, elas vão aparecer aqui mesmo, nesse link, para você baixar.`}</p>{status==='selecao_finalizada'&&<div className="grid client-selected-summary">{selectedPhotos.map(photo=><div className="frame protegida" key={photo.id}><img src={photo.url} alt="Foto selecionada"/></div>)}</div>}</div>}
    {status==='aguardando_selecao'&&<><p className="client-selection-help">Clique nas fotos que você mais gostou. Pode escolher quantas quiser, e mudar de ideia antes de enviar.</p><div className="grid client-gallery-grid" id="grid-selecao">{photos.map((photo,index)=><div className={`frame protegida foto-selecionavel ${selected.has(photo.id)?'marcada':''}`} key={photo.id} onClick={()=>setLightbox(index)}><img src={photo.url} alt="Foto do ensaio"/><button className="check-box" onClick={event=>{event.stopPropagation();toggle(photo.id)}} aria-label={selected.has(photo.id)?'Remover da seleção':'Adicionar à seleção'}>{selected.has(photo.id)?'✓':''}</button></div>)}</div><div className="barra-selecao" id="barra-selecao"><span className="footer-mono">{selected.size} foto(s) selecionada(s)</span><button className="btn btn-accent" onClick={()=>selected.size?setConfirm(true):(setError(true),setMessage('Selecione pelo menos uma fotografia.'))}>Enviar seleção</button></div>{message&&<p className={`msg ${error?'erro':''}`}>{message}</p>}</>}
  </div>
  {lightbox!==null&&photos[lightbox]&&<div className="lightbox is-open" id="lightbox-selecao" onClick={event=>{if(event.target===event.currentTarget)setLightbox(null)}}><div className="lightbox-top"><div><p className="lightbox-title">Foto ampliada</p><p className="lightbox-counter">{lightbox+1} / {photos.length}</p></div><button className="lightbox-close" onClick={()=>setLightbox(null)} aria-label="Fechar visualizador">✕</button></div><button className="lightbox-arrow lightbox-arrow-left" onClick={()=>setLightbox((lightbox-1+photos.length)%photos.length)}>‹</button><div className="lightbox-stage protegida"><img src={photos[lightbox].url} alt="Foto ampliada"/></div><button className="lightbox-arrow lightbox-arrow-right" onClick={()=>setLightbox((lightbox+1)%photos.length)}>›</button><div className="lightbox-actions"><button className="btn btn-accent" onClick={()=>toggle(photos[lightbox].id)}>{selected.has(photos[lightbox].id)?'✓ Selecionada — remover':'Selecionar esta foto'}</button></div></div>}
  {confirm&&<div className="selection-confirm-overlay" aria-hidden="false" onClick={event=>{if(event.target===event.currentTarget)setConfirm(false)}}><div className="selection-confirm-dialog" role="dialog" aria-modal="true"><p className="section-eyebrow">Confirmar seleção</p><h2>Finalizar sua seleção?</h2><p className="selection-confirm-copy">Depois de confirmar, sua seleção será enviada ao fotógrafo para edição.</p><div className="selection-confirm-count">{selected.size} fotografia{selected.size===1?'':'s'} selecionada{selected.size===1?'':'s'}</div><div className="selection-confirm-actions"><button type="button" className="btn" onClick={()=>setConfirm(false)}>Voltar e conferir</button><button type="button" className="btn btn-accent" onClick={saveSelection} disabled={busy}>Confirmar seleção</button></div><p className={`msg ${error?'erro':''}`}>{message}</p></div></div>}
  </main>;
}
