'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
type Slide={url:string;alt?:string;published?:boolean;sort_order?:number;focus_x?:number;focus_y?:number};
function mediaUrl(value:unknown,fallback:string){
  const url=String(value||fallback).trim();
  if(/^https?:\/\//i.test(url))return url;
  const normalized=url.replace(/^\/+/, '');
  if(/^legacy\//i.test(normalized))return `/${normalized}`;
  if(/^images\//i.test(normalized))return `/legacy/${normalized}`;
  return `/legacy/${normalized}`;
}
export function HomeHero({hero}:{hero:Record<string,any>}){const slides=useMemo(()=>((Array.isArray(hero.slides)?hero.slides:[]) as Slide[]).filter(s=>s.url&&s.published!==false).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),[hero.slides]);const useSlides=hero.mode==='slideshow'&&slides.length>0;const [current,setCurrent]=useState(0);useEffect(()=>{if(!useSlides||slides.length<2)return;const timer=setInterval(()=>setCurrent(value=>(value+1)%slides.length),Math.max(2000,Number(hero.slide_interval||5)*1000));return()=>clearInterval(timer)},[useSlides,slides.length,hero.slide_interval]);const title=String(hero.title||'Retratos que revelam você').trim();const words=title.split(/\s+/);const last=words.pop();const focusStyle={'--hero-focus-desktop':`${hero.static_focus_x??50}% ${hero.static_focus_y??50}%`,'--hero-focus-mobile':`${hero.static_mobile_focus_x??hero.static_focus_x??50}% ${hero.static_mobile_focus_y??hero.static_focus_y??50}%`} as React.CSSProperties;return <header className="hero"><div className="hero-media">{useSlides? <div className="hero-slideshow is-active is-ready" aria-hidden="false">{slides.map((slide,index)=><div key={slide.url} className={`hero-slide${index===current?' is-visible':''}`} style={{backgroundImage:`url('${mediaUrl(slide.url,'images/hero-bg.jpg')}')`,backgroundPosition:`${slide.focus_x??50}% ${slide.focus_y??50}%`}}/>)}</div>:<picture><source media="(max-width: 899px)" srcSet={mediaUrl(hero.mobile_image,'images/hero-bg-mobile.jpg')}/><img src={mediaUrl(hero.desktop_image,'images/hero-bg.jpg')} alt={hero.image_alt||'Rangel Santos, fotógrafo'} className="hero-photo" style={focusStyle}/></picture>}<div className="hero-overlay"/></div><div className="container"><p id="hero-eyebrow" className="hero-eyebrow">{hero.eyebrow||''}</p><h1 id="hero-title" className="hero-title">{words.join(' ')}<br/><em>{last}</em></h1><p id="hero-description" className="hero-sub">{hero.description||''}</p><div className="hero-actions" style={{marginTop:36,display:'flex',gap:16,flexWrap:'wrap'}}><Link id="hero-primary-button" href={hero.primary_button?.url||'/galeria'} className="btn">{hero.primary_button?.text||'Ver galeria'}</Link><Link id="hero-secondary-button" href={hero.secondary_button?.url||'/contato'} className="btn btn-accent">{hero.secondary_button?.text||'Agendar sessão'}</Link></div><div className="hero-meta">{Array.isArray(hero.meta)&&hero.meta.map((item:any,index:number)=><div key={index}>{typeof item==='string'?<span>{item}</span>:<><strong>{item.label||''}</strong><span>{item.value||item.text||''}</span></>}</div>)}</div></div></header>}
