'use client';
import { FormEvent,useState } from 'react';
import { createSupabaseBrowserClient } from '@/lib/supabase/browser';

export function ContactForm({types,submitLabel}:{types:string[];submitLabel:string}){
  const [status,setStatus]=useState<{text:string;kind:string}>({text:'',kind:''});const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const website=String(data.get('website')||'').trim();if(website){form.reset();setStatus({text:'Mensagem enviada! Em breve entro em contato.',kind:'sucesso'});return}const nome=String(data.get('nome')||'').trim(),email=String(data.get('email')||'').trim().toLowerCase(),tipo=String(data.get('tipo')||'').trim(),mensagem=String(data.get('mensagem')||'').trim();if(!nome||!email||!mensagem){setStatus({text:'Preencha nome, e-mail e mensagem.',kind:'erro'});return}if(nome.length>120||email.length>254||tipo.length>100||mensagem.length>3000){setStatus({text:'Revise os campos: há informação acima do limite permitido.',kind:'erro'});return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)){setStatus({text:'Informe um e-mail válido.',kind:'erro'});return}setBusy(true);setStatus({text:'',kind:''});try{const client=createSupabaseBrowserClient();const {data:result,error}=await client.functions.invoke('contact-notifications',{body:{nome,email,tipo,mensagem,website:''}});if(error||!result?.ok)throw error||new Error(result?.error);form.reset();setStatus({text:'Mensagem enviada! Em breve entro em contato.',kind:'sucesso'})}catch{setStatus({text:'Não foi possível enviar. Tente novamente em instantes.',kind:'erro'})}finally{setBusy(false)}}
  return <form id="contato-form" noValidate onSubmit={submit}><div className="field"><label htmlFor="nome">Nome</label><input type="text" id="nome" name="nome" maxLength={120} autoComplete="name" required/></div><div className="field"><label htmlFor="email">E-mail</label><input type="email" id="email" name="email" maxLength={254} autoComplete="email" required/></div><div className="field"><label htmlFor="tipo">Tipo de sessão</label><select id="tipo" name="tipo">{types.map(type=><option key={type}>{type}</option>)}</select></div><div className="field"><label htmlFor="mensagem">Mensagem</label><textarea id="mensagem" name="mensagem" rows={5} maxLength={3000} required/></div><div className="contact-honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input type="text" id="website" name="website" tabIndex={-1} autoComplete="off"/></div><button type="submit" className="btn" disabled={busy} aria-busy={busy}>{busy?'Enviando...':submitLabel}</button><p className={`msg ${status.kind}`}>{status.text}</p></form>
}
