begin;

create extension if not exists pgcrypto;

create table if not exists public.gallery_trails (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  cover_url text,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.categories add column if not exists trail_id uuid references public.gallery_trails(id) on delete set null;
create index if not exists categories_trail_id_idx on public.categories(trail_id);

create table if not exists public.admin_activity (
  id bigint generated by default as identity primary key,
  activity_type text not null,
  title text not null,
  detail text,
  entity_type text,
  entity_id text,
  severity text not null default 'info' check (severity in ('info','success','warning','danger')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_activity_created_at_idx on public.admin_activity(created_at desc);

alter table public.ensaios add column if not exists selected_photo_numbers jsonb not null default '[]'::jsonb;
alter table public.ensaios add column if not exists selection_completed_at timestamptz;
alter table public.ensaios add column if not exists selection_cleaned_at timestamptz;
alter table public.ensaios add column if not exists delivered_at timestamptz;
alter table public.ensaios add column if not exists expires_at timestamptz;
alter table public.ensaios add column if not exists expiry_days integer not null default 30;
alter table public.ensaios add column if not exists expiry_warning_7_sent_at timestamptz;
alter table public.ensaios add column if not exists expiry_warning_3_sent_at timestamptz;
alter table public.ensaios add column if not exists expiry_warning_1_sent_at timestamptz;
alter table public.ensaios add column if not exists expired_at timestamptz;
alter table public.ensaios add column if not exists deletion_scheduled_at timestamptz;
alter table public.ensaios add column if not exists selection_thank_you_image_url text;
alter table public.ensaios add column if not exists selection_thank_you_message text;
create index if not exists ensaios_expires_at_idx on public.ensaios(expires_at) where expires_at is not null;

insert into public.gallery_trails(name,slug,description,sort_order)
values
  ('Retratos & Corporativo','retratos-corporativo','Estúdio, externo e ensaios corporativos.',10),
  ('Autoestima & Sensual','autoestima-sensual','Ensaios de autoestima, sensual e boudoir.',20)
on conflict (slug) do nothing;

alter table public.gallery_trails enable row level security;
alter table public.admin_activity enable row level security;

drop policy if exists "gallery_trails_public_read" on public.gallery_trails;
create policy "gallery_trails_public_read" on public.gallery_trails for select using (published = true or auth.role() = 'authenticated');
drop policy if exists "gallery_trails_admin_write" on public.gallery_trails;
create policy "gallery_trails_admin_write" on public.gallery_trails for all to authenticated using (true) with check (true);
drop policy if exists "admin_activity_authenticated" on public.admin_activity;
create policy "admin_activity_authenticated" on public.admin_activity for all to authenticated using (true) with check (true);

create or replace function public.log_admin_activity(
  p_activity_type text,
  p_title text,
  p_detail text default null,
  p_entity_type text default null,
  p_entity_id text default null,
  p_severity text default 'info',
  p_metadata jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=public as $$
declare new_id bigint;
begin
  insert into public.admin_activity(activity_type,title,detail,entity_type,entity_id,severity,metadata)
  values(p_activity_type,p_title,p_detail,p_entity_type,p_entity_id,p_severity,p_metadata)
  returning id into new_id;
  return new_id;
end;
$$;
revoke all on function public.log_admin_activity(text,text,text,text,text,text,jsonb) from public;
grant execute on function public.log_admin_activity(text,text,text,text,text,text,jsonb) to authenticated;

create or replace function public.prepare_session_delivery_expiry()
returns trigger language plpgsql as $$
begin
  if new.status in ('entregue','pronto','ready','delivered') and
     (old.status is distinct from new.status or new.delivered_at is null) then
    new.delivered_at := coalesce(new.delivered_at,now());
    new.expires_at := coalesce(new.expires_at,new.delivered_at + make_interval(days=>greatest(new.expiry_days,1)));
  end if;
  return new;
end;
$$;
drop trigger if exists ensaios_prepare_expiry on public.ensaios;
create trigger ensaios_prepare_expiry before update on public.ensaios for each row execute function public.prepare_session_delivery_expiry();

commit;
